name: Daily URA Vacant Sites Download 

on: 
  schedule: 
    # Run daily at 9:00 AM UTC (adjust time as needed) 
    - cron: "0 9 * * *"  # Fixed cron expression - was missing day of month and day of week
  workflow_dispatch: 
    # This enables manual triggering of the workflow through GitHub UI

jobs: 
  download: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout repository 
        uses: actions/checkout@v4  # Updated from v3 to v4
        
      - name: Set up Python 
        uses: actions/setup-python@v4 
        with: 
          python-version: "3.10" 
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
                
      - name: Run download script 
        run: python ura_tracker_with_form.py
        
      - name: Upload Excel file as artifact 
        uses: actions/upload-artifact@v4  # Updated from v3 to v4
        with: 
          name: ura-vacant-sites 
          path: ura_land_sales_data/*.xlsx 
          retention-days: 7 # Keep files for 7 days 
          
      - name: Commit and push if there are changes 
        run: | 
          git config --global user.name 'GitHub Actions' 
          git config --global user.email 'actions@github.com' 
          git add ura_land_sales_data/ 
          # Only attempt to commit if there are changes 
          git diff --staged --quiet || (git commit -m "Auto-update vacant sites data $(date +'%Y-%m-%d')" && git push)
